<?php if (!isset($_SESSION[""])) {
   session_start();
}
if (isset($_SESSION['data-user'])) {
   header("Location: superadmin/");
   exit();
} ?>

<!DOCTYPE html>
<html lang="en">

<head>
   <title>Bengkel Online</title>
   <meta charset="utf-8">
   <meta name="viewport" content="width=device-width, initial-scale=1">
   <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
   <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
   <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
   <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</head>
<style>
   .color-change-3x {
      -webkit-animation: color-change-3x 4s linear infinite alternate both;
      animation: color-change-3x 4s linear infinite alternate both;
   }

   /* ----------------------------------------------
 * Generated by Animista on 2021-6-2 11:20:23
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

   /**
 * ----------------------------------------
 * animation color-change-3x
 * ----------------------------------------
 */
   @-webkit-keyframes color-change-3x {
      0% {
         background: #19dcea;
      }

      50% {
         background: #b22cff;
      }

      100% {
         background: #ea2222;
      }
   }

   @keyframes color-change-3x {
      0% {
         background: #19dcea;
      }

      50% {
         background: #b22cff;
      }

      100% {
         background: #ea2222;
      }
   }
</style>

<body class="color-change-3x">
   <div class="container  shadow p-3 mb-3 bg-white">
      <!-- corousell -->
      <div id="demo" class="carousel slide" data-ride="carousel">

         <!-- Indicators -->
         <ul class="carousel-indicators">
            <li data-target="#demo" data-slide-to="0" class="active"></li>
            <li data-target="#demo" data-slide-to="1"></li>
            <li data-target="#demo" data-slide-to="2"></li>
         </ul>

         <!-- The slideshow -->
         <div class="carousel-inner">
            <div class="carousel-item active">
               <img src="image/01.jpg" width="100%" height="100%" alt="Bengkel">
            </div>
            <div class="carousel-item">
               <img src="image/02.jpg" width="100%" height="100%" alt="Bengkel">
            </div>
            <div class="carousel-item">
               <img src="image/01.jpg" width="100%" height="100%" alt="Bengkel">
            </div>
         </div>

         <!-- Left and right controls -->
         <a class="carousel-control-prev" href="#demo" data-slide="prev">
            <span class="carousel-control-prev-icon"></span>
         </a>
         <a class="carousel-control-next" href="#demo" data-slide="next">
            <span class="carousel-control-next-icon"></span>
         </a>

      </div>
      <!-- corousell tutup -->


      <?php
      include "superadmin/konektor.php";
      $id_bengkel = $_GET['id'];
      $bengkel = mysqli_fetch_assoc(mysqli_query($konektor, "SELECT * FROM bengkel WHERE id_bengkel = '$id_bengkel'"));
      ?>
      <div class="jumbotron text-center">
         <h4><?= $bengkel['nama_bengkel'] ?></h4>
         <br>
         <div class="row">
            <div class="col-sm-4">
               <img src="image/<?php echo $id_bengkel ?>.jpg" alt="" width="100%">
            </div>
            <div class="col-sm-8">
               <table>
                  <tr>
                     <th width="150px" style="text-align: left">Nama</th>
                     <td style="text-align: left">: <?= $bengkel['nama_bengkel'] ?></td>
                  </tr>
                  <tr>
                     <th width="150px" style="text-align: left">Nama Pemilik</th>
                     <td style="text-align: left">: <?= $bengkel['nama_pemilik'] ?></td>
                  </tr>
                  <tr>
                     <th width="150px" style="text-align: left">No HP</th>
                     <td style="text-align: left">: <?= $bengkel['no_hp'] ?></td>
                  </tr>
                  <tr>
                     <th width="150px" style="text-align: left">Alamat</th>
                     <td style="text-align: left">: <?= $bengkel['alamat'] ?></td>
                  </tr>
                  <tr>
                     <th width="150px" style="text-align: left">Jam Buka</th>
                     <td style="text-align: left">: <?= $bengkel['jam_buka'] ?></td>
                  </tr>
                  <tr>
                     <th width="150px" style="text-align: left">Jam Tutup</th>
                     <td style="text-align: left">: <?= $bengkel['jam_tutup'] ?></td>
                  </tr>
                  <tr>
                     <th width="150px" style="text-align: left">Deskripsi</th>
                     <td style="text-align: left">: <?= $bengkel['deskripsi'] ?></td>
                  </tr>
                  <tr>
                     <?php
                     $lok = mysqli_fetch_assoc(mysqli_query($konektor, "SELECT * FROM lokasi, bengkel WHERE bengkel.id_bengkel = lokasi.id_bengkel AND lokasi.id_bengkel = '" . $bengkel['id_bengkel'] . "'"))
                     ?>
                     <th colspan="2" width="150px" style="text-align: left"> <br> <a href="https://www.google.com/maps/place/<?= $lok['latitude'] ?>,<?= $lok['longtitude'] ?>" class="btn btn-primary" style="float: left"> Petunjuk Jalan</a></th>
                  </tr>
               </table>
            </div>
         </div>
      </div>

</body>

</html>