<?php if (!isset($_SESSION[""])) {
   session_start();
}
if (isset($_SESSION['data-user'])) {
   header("Location: superadmin/");
   exit();
} ?>

<!DOCTYPE html>
<html lang="en">

<head>
   <title>Bengkel Online</title>
   <meta charset="utf-8">
   <meta name="viewport" content="width=device-width, initial-scale=1">
   <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
   <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
   <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
   <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
   <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css">
</head>
<style>
   .color-change-3x {
      -webkit-animation: color-change-3x 4s linear infinite alternate both;
      animation: color-change-3x 4s linear infinite alternate both;
   }

   /* ----------------------------------------------
 * Generated by Animista on 2021-6-2 11:20:23
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

   /**
 * ----------------------------------------
 * animation color-change-3x
 * ----------------------------------------
 */
   @-webkit-keyframes color-change-3x {
      0% {
         background: #19dcea;
      }

      50% {
         background: #b22cff;
      }

      100% {
         background: #ea2222;
      }
   }

   @keyframes color-change-3x {
      0% {
         background: #19dcea;
      }

      50% {
         background: #b22cff;
      }

      100% {
         background: #ea2222;
      }
   }
</style>

<body class="color-change-3x">
   <div class="container  shadow p-3 mb-3" style="background-color: #f4f3f5;">

      <!-- Navbar -->
      <nav class="navbar navbar-light bg-light">
         <div class="container-fluid justify-content-end">
            <a class="navbar-brand" style="font-size: 16px;" href="auth/">
               <i class="bi bi-box-arrow-in-right" style="font-size: 22px;"></i> Login
            </a>
         </div>
      </nav>
      <!-- End Navbar -->

      <!-- corousell -->
      <div id="demo" class="carousel slide" data-ride="carousel">

         <!-- Indicators -->
         <ul class="carousel-indicators">
            <li data-target="#demo" data-slide-to="0" class="active"></li>
            <li data-target="#demo" data-slide-to="1"></li>
            <li data-target="#demo" data-slide-to="2"></li>
         </ul>

         <!-- The slideshow -->
         <div class="carousel-inner">
            <div class="carousel-item active">
               <img src="image/01.jpg" width="100%" height="100%" alt="Bengkel">
            </div>
            <div class="carousel-item">
               <img src="image/02.jpg" width="100%" height="100%" alt="Bengkel">
            </div>
            <div class="carousel-item">
               <img src="image/01.jpg" width="100%" height="100%" alt="Bengkel">
            </div>
         </div>

         <!-- Left and right controls -->
         <a class="carousel-control-prev" href="#demo" data-slide="prev">
            <span class="carousel-control-prev-icon"></span>
         </a>
         <a class="carousel-control-next" href="#demo" data-slide="next">
            <span class="carousel-control-next-icon"></span>
         </a>

      </div>
      <!-- corousell tutup -->
      <br>
      <div class="container">
         <div class="col-sm-12 mb-3">
            <div class="row">
               <div class="col-sm-8"><input type="text" id="myFilter" class="form-control" onkeyup="myFunction()" placeholder="Pencarian berdasarkan nama bengkel / nama tempat"></div>
               <div class="col-sm-2"><a href="https://www.google.com/maps/search/tambal+ban+terdekat/@-10.1650088,123.6292933,13.75z" class="btn btn-primary" target="_blank">Bengkel Terdekat</a></div>
               <div class="col-sm-2"><a href="map" class="btn btn-primary">Peta</a></div>
            </div>
         </div>
         <!-- card Nyaris -->
         <div class="row mb-2" id="myItems">
            <?php
            include "superadmin/konektor.php";
            $sql = mysqli_query($konektor, "SELECT * FROM bengkel");
            while ($r = mysqli_fetch_array($sql)) { ?>
               <div class="col-sm-6 col-md-6 col-lg-4 col-xl-3 mb-3">

                  <div class="card shadow-sm" style="width:100%" style="max-height: 300px; height: 300px;">
                     <?php
                     //Display image
                     $file = $r['id_bengkel'];
                     if (file_exists("superadmin/berkas/$file.jpg")) {
                     ?>
                        <div class="w-100" style="height: 200px; background-image: url('superadmin/berkas/<?= $r['image']; ?>'); background-position: top; background-size: 100%;">
                        </div>
                     <?php
                     } else { ?>

                        <div class="w-100" style="height: 200px; background-image: url('superadmin/berkas/kosong.png'); background-position: center; background-size: 100%;"></div>
                     <?php
                     }
                     ?>
                     <div class="card-body text-center" style="background-color: #3ef3081f;">
                        <h6 class="card-title ">
                           <?php
                           $isi3 = $r['nama_bengkel'];
                           $Lebar = strlen($isi3);
                           if ($Lebar > 15) {
                              echo substr($isi3, 0, 15); ?>...<?php
                                                            } else {
                                                               echo $isi3;
                                                            }
                                                               ?>
                        </h6>
                        <hr class="m-0">

                        <small id="alamat">
                           <strong>Alamat : </strong><?= $r['alamat'] ?>
                        </small>
                        <small><strong>Jam Buka : </strong><?= $r['jam_buka'] ?> s/d <?= $r['jam_tutup'] ?> WITA</small>
                        <br>
                        <small class="card-text"><a href="detail_bengkel.php?id=<?= $r['id_bengkel'] ?>"><u>Selengkapnya...</u></a></small>
                     </div>
                  </div>

                  <br>
               </div>

            <?php
            }
            ?>
         </div>
         <!-- card Nyaris Tutup -->
      </div>
   </div>
   <script>
      function myFunction() {
         var input, filter, cards, cardContainer, h5, title, i;
         input = document.getElementById("myFilter");
         filter = input.value.toUpperCase();
         cardContainer = document.getElementById("myItems");
         cards = cardContainer.getElementsByClassName("card");
         for (i = 0; i < cards.length; i++) {
            title = cards[i].querySelector(".card-body");
            if (title.innerText.toUpperCase().indexOf(filter) > -1) {
               cards[i].style.display = "";
            } else {
               cards[i].style.display = "none";
            }
         }
      }
   </script>
</body>

</html>