<?php
if (!isset($_SESSION[""])) {
  session_start();
}
if (!isset($_SESSION['data-user'])) {
  header("Location: ../auth/");
  exit();
}
error_reporting(~E_NOTICE & ~E_DEPRECATED);
include 'konektor.php';
include 'enkripsiVariabel.php';
if (isset($_SESSION["time-message"])) {
  if ((time() - $_SESSION["time-message"]) > 2) {
    if (isset($_SESSION["message-success"])) {
      unset($_SESSION["message-success"]);
    }
    if (isset($_SESSION["message-info"])) {
      unset($_SESSION["message-info"]);
    }
    if (isset($_SESSION["message-warning"])) {
      unset($_SESSION["message-warning"]);
    }
    if (isset($_SESSION["message-danger"])) {
      unset($_SESSION["message-danger"]);
    }
    if (isset($_SESSION["message-dark"])) {
      unset($_SESSION["message-dark"]);
    }
    unset($_SESSION["time-alert"]);
  }
}

?>

<!DOCTYPE html>
<html lang="en">

<head>
  <title>Tambal Ban Online</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
  <link rel="shortcut icon" href="../image/logo.png">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
  <meta name='viewport' content='width=device-width, initial-scale=1'>
  <script src='https://kit.fontawesome.com/a076d05399.js'></script>
  <!--Get your own code at fontawesome.com-->
  <script type="text/javascript" src="chartjs294/Chart.js"></script>
  <script src="../assets/sweetalert/dist/sweetalert2.all.min.js"></script>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css">
  <style>
    .swing-in-top-fwd {
      -webkit-animation: swing-in-top-fwd 4s cubic-bezier(0.175, 0.885, 0.320, 1.275) both;
      animation: swing-in-top-fwd 4s cubic-bezier(0.175, 0.885, 0.320, 1.275) both;
    }

    /* ----------------------------------------------
    * Generated by Animista on 2020-12-11 17:15:23
    * Licensed under FreeBSD License.
    * See http://animista.net/license for more info. 
    * w: http://animista.net, t: @cssanimista
    * ---------------------------------------------- */

    /**
    * ----------------------------------------
    * animation swing-in-top-fwd
    * ----------------------------------------
    */
    @-webkit-keyframes swing-in-top-fwd {
      0% {
        -webkit-transform: rotateX(-100deg);
        transform: rotateX(-100deg);
        -webkit-transform-origin: top;
        transform-origin: top;
        opacity: 0;
      }

      100% {
        -webkit-transform: rotateX(0deg);
        transform: rotateX(0deg);
        -webkit-transform-origin: top;
        transform-origin: top;
        opacity: 1;
      }
    }

    @keyframes swing-in-top-fwd {
      0% {
        -webkit-transform: rotateX(-100deg);
        transform: rotateX(-100deg);
        -webkit-transform-origin: top;
        transform-origin: top;
        opacity: 0;
      }

      100% {
        -webkit-transform: rotateX(0deg);
        transform: rotateX(0deg);
        -webkit-transform-origin: top;
        transform-origin: top;
        opacity: 1;
      }
    }
  </style>
</head>

<body style="background-image: url(../image/1.png);">
  <?php if (isset($_SESSION["message-success"])) { ?>
    <div class="message-success" data-message-success="<?= $_SESSION["message-success"] ?>"></div>
  <?php }
  if (isset($_SESSION["message-info"])) { ?>
    <div class="message-info" data-message-info="<?= $_SESSION["message-info"] ?>"></div>
  <?php }
  if (isset($_SESSION["message-warning"])) { ?>
    <div class="message-warning" data-message-warning="<?= $_SESSION["message-warning"] ?>"></div>
  <?php }
  if (isset($_SESSION["message-danger"])) { ?>
    <div class="message-danger" data-message-danger="<?= $_SESSION["message-danger"] ?>"></div>
  <?php } ?>
  <nav class="navbar fixed-top navbar-expand-md bg-info navbar-info">
    <img src="../image/logo.png" width="20px" height="20px">
    <a class="navbar-brand text-light font-weight-bolder " href="#">Tambal Ban Online</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="collapsibleNavbar">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link text-light font-weight-bolder " href="#" data-toggle="modal" data-target="#myModalAdmin"><i class="bi bi-person"></i> Admin</a>
        </li>
        <li class="nav-item">
          <a class="nav-link text-light font-weight-bolder " href="#" data-toggle="modal" data-target="#myModalLokasi">
            <i class="bi bi-geo-alt"></i> Lokasi
            <span class="badge badge-primary">
              <?php $datab1 = mysqli_query($konektor, "select count(id_lokasi) as jumlah from lokasi");
              if (mysqli_num_rows($datab1) > 0) {
                while ($db1 = mysqli_fetch_array($datab1)) {
                  echo $db1['jumlah'];
                }
              } //Data ditemukan dan ditampilkan ke layar
              else {
                echo '0';
              }
              ?>
            </span>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link text-light font-weight-bolder " href="#" data-toggle="modal" data-target="#myModalBengkel">
            <i class="bi bi-gear-wide-connected"></i> Bengkel
            <span class="badge badge-primary">
              <?php $datab2 = mysqli_query($konektor, "select count(id_bengkel) as jumlah from bengkel");
              if (mysqli_num_rows($datab1) > 0) {
                while ($db2 = mysqli_fetch_array($datab2)) {
                  echo $db2['jumlah'];
                }
              } //Data ditemukan dan ditampilkan ke layar 
              else {
                echo '0';
              } ?>
            </span>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link text-light font-weight-bolder " href="../auth/signout.php"><i class="bi bi-box-arrow-left"></i> Logout</a>
        </li>
      </ul>
    </div>
  </nav>
  <div class="container">
    <div class="row">
      <div class="col-md-6">
        <!--konten kolom 1 -->
        <div class="row mt-5">
          <div class="col-md-12 mt-5">
            <div class="alert alert-warning swing-in-top-fwd font-weight-bold">
              <?php
              echo "Selamat Datang " . $_SESSION['data-user']['username']; //Berhasil Login 
              ?>
            </div>
          </div>
        </div>
        <?php
        //notifikasi pesan 
        if (isset($_GET['pesan'])) {
          if ($_GET['pesan'] == "tersimpan") { ?>
            <div class="row">
              <div class="col-sm-12">
                <div class="alert alert-success swing-in-top-fwd"> <i style='font-size:24px' class='fas'>&#xf00c;</i> <?php
                                                                                                                      echo "Data baru telah disimpan"; ?> </div>
              </div>
            </div>
          <?php } else if ($_GET['pesan'] == "ubah") {  ?>
            <div class="row">
              <div class="col-sm-12">
                <div class="alert alert-primary swing-in-top-fwd"> <i style='font-size:20px' class='far'>&#xf059;</i> <?php
                                                                                                                      echo "Data yang Anda pilih telah diubah";
                                                                                                                      ?> </div>
              </div>
            </div>
          <?php } else if ($_GET['pesan'] == "hapus") { ?>
            <div class="row">
              <div class="col-sm-12">
                <div class="alert alert-danger swing-in-top-fwd"> <i style='font-size:20px' class='fas'>&#xf057;</i> <?php
                                                                                                                      echo "Data yang Anda pilih telah dihapus";  ?> </div>
              </div>
            </div>
          <?php } else if ($_GET['pesan'] == "duplikat") { ?>
            <div class="row">
              <div class="col-sm-12">
                <div class="alert alert-danger swing-in-top-fwd"> <i style='font-size:20px' class='fas'>&#xf057;</i> <?php
                                                                                                                      echo "maaf, data tidak disimpan karena terjadi duplikasi pada atribut Username, silahkan masukan Username yang baru";
                                                                                                                      ?> </div>
              </div>
            </div>
          <?php } else if ($_GET['pesan'] == "fileterkirim") {
            $name = buka($_GET['name']);
            $size = buka($_GET['size']);
            $type = buka($_GET['type']); ?>
            <div class="row">
              <div class="col-sm-12">
                <div class="alert alert-success swing-in-top-fwd"> <i class='fas fa-check' style='font-size:14px;color:green'></i>
                  <?php
                  echo "file telah berasil di kirim. berikut ini informasinya: 
                  <br>nama file: $name
                  <br>ukuran file: $size
                  <br>type file: $type";  ?> </div>
              </div>
            </div>
          <?php } else if ($_GET['pesan'] == "filegagalterkirim") {
            $name = buka($_GET['name']);
            $size = buka($_GET['size']);
            $type = buka($_GET['type']); ?>
            <div class="row">
              <div class="col-sm-12">
                <div class="alert alert-danger swing-in-top-fwd"> <i style='font-size:20px' class='fas'>&#xf057;</i>
                  <?php
                  echo "file anda gagal di kirim. berikut ini informasinya: 
                  <br>nama file: $name
                  <br>ukuran file: $size
                  <br>type file: $type"; ?> </div>
              </div>
            </div>
        <?php }
        } ?>
        <!-- The Modal Display Admin -->
        <div class="modal fade" id="myModalAdmin">
          <div class="modal-dialog modal-xl">
            <div class="modal-content">

              <!-- Modal Header -->
              <div class="modal-header" style="background-color: #47AFAF;">
                <h4 class="modal-title text-light"><i style='font-size:24px' class='fas'>&#xf2bd;</i> Daftar Admin</h4>
                <button type="button" class="close" data-dismiss="modal">&times;</button>
              </div>

              <!-- Modal body -->
              <div class="modal-body">
                <a href="#" class="btn btn-success" data-toggle="modal" data-target="#myModalTDA"><i style='font-size:20px' class='fas'>&#xf0fe;</i> </a>
                <a href="report/lapAdminSeluruh.php" target="_blank" class="btn btn-success"><i style='font-size:20px' class='fas'>&#xf1c1;</i> </a>
                <a href="excel/eAdmin.php" class="btn btn-success"> <i style='font-size:20px' class='far'>&#xf1c3;</i> </a> <br><br>
                <input class="form-control" id="myInputAdmin" type="text" placeholder="Cari..">
                <br>
                <div class="table-responsive">
                  <table class="table table-striped table-hover table-sm" id="myTableAdmin">
                    <thead>
                      <tr>
                        <th>NO</th>
                        <th>Nama</th>
                        <th>Email</th>
                        <th>Username</th>
                        <th>Sandi</th>
                        <th>Aksi</th>
                      </tr>
                    </thead>
                    <tbody>
                      <?php
                      $no = 1;
                      $data = mysqli_query($konektor, "select * from admin");
                      while ($d = mysqli_fetch_array($data)) {
                      ?>
                        <tr>
                          <td><?= $no++; ?></td>
                          <td><?php echo $d['nama_admin']; ?></td>
                          <td><?php echo $d['emel']; ?></td>
                          <td><?php echo $d['username']; ?></td>
                          <td><?php echo $d['sandi']; ?></td>
                          <td>
                            <a href="#" data-toggle="modal" data-target="#myModalUDA<?php echo $d['id_admin']; ?>"><i style='font-size:14px' class='fas'>&#xf044;</i></a>
                            <a onclick="return confirm('Yakin ingin menghapus data sekarang?');" href="delete/deleteAdmin.php?id=<?php echo kunci($d['id_admin']); ?>"><i style='font-size:14px' class='fas'>&#xf1f8;</i></a>

                          </td>
                        </tr>

                        <!-- The Modal Ubah Data Admin -->
                        <div class="modal fade" id="myModalUDA<?php echo $d['id_admin']; ?>">
                          <div class="modal-dialog modal-lg">
                            <div class="modal-content">

                              <!-- Modal Header -->
                              <div class="modal-header">
                                <h4 class="modal-title">Ubah Data Admin</h4>
                                <button type="button" class="close" data-dismiss="modal">&times;</button>
                              </div>

                              <!-- Modal body -->
                              <div class="modal-body">

                                <!-- Form ubah data menyatu dengan form index-->
                                <form onsubmit="return confirm('Yakin ingin mengubah data sekarang?');" method="post" action="update/updateAdmin.php">
                                  <!--Hidden Field idadmin -->
                                  <input type="hidden" name="id_admin" value="<?php echo $d['id_admin']; ?>">
                                  <!-- Edit Text Field-->
                                  <div class="input-group mb-2">
                                    <div class="input-group-prepend">
                                      <span class="input-group-text">Nama Admin</span>
                                    </div>
                                    <input pattern="[A-Za-z ]+" type="text" class="form-control" required name="nama_admin" value="<?php echo $d['nama_admin']; ?>">
                                  </div>

                                  <!-- Edit Text Field-->
                                  <div class="input-group mb-2">
                                    <div class="input-group-prepend">
                                      <span class="input-group-text">Email</span>
                                    </div>
                                    <input type="text" class="form-control" required name="emel" value="<?php echo $d['emel']; ?>">
                                  </div>

                                  <!-- Edit Text Field-->
                                  <div class="input-group mb-2">
                                    <div class="input-group-prepend">
                                      <span class="input-group-text">Username</span>
                                    </div>
                                    <input type="text" class="form-control" required name="username" value="<?php echo $d['username']; ?>">
                                  </div>

                                  <!-- Edit Text Field-->
                                  <div class="input-group mb-2">
                                    <div class="input-group-prepend">
                                      <span class="input-group-text">Sandi</span>
                                    </div>
                                    <input type="password" class="form-control" required name="sandi" value="<?php echo $d['sandi']; ?>">
                                  </div>

                                  <!-- Akhir form ubah data -->

                              </div>

                              <!-- Modal footer -->
                              <div class="modal-footer">
                                <!-- Input Button-->
                                <input class="btn btn-success" type="submit" value="Simpan"></form>
                                <button type="button" class="btn btn-danger" data-dismiss="modal">Tutup</button>
                              </div>
                            </div>
                          </div>
                        </div>

                      <?php } ?>
                    </tbody>
                  </table>
                </div>

                <script>
                  $(document).ready(function() {
                    $("#myInputAdmin").on("keyup", function() {
                      var value = $(this).val().toLowerCase();
                      $("#myTableAdmin tr").filter(function() {
                        $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
                      });
                    });
                  });
                </script>
              </div>

              <!-- Modal footer -->
              <div class="modal-footer">
                <button type="button" class="btn btn-danger" data-dismiss="modal">Tutup</button>
              </div>
            </div>
          </div>
        </div>

        <!-- The Modal Tambah Data Admin -->
        <div class="modal fade" id="myModalTDA">
          <div class="modal-dialog modal-md">
            <div class="modal-content">

              <!-- Modal Header -->
              <div class="modal-header">
                <h4 class="modal-title"><i style='font-size:20px' class='fas'>&#xf0fe;</i> Tambah Data Admin </h4>
                <button type="button" class="close" data-dismiss="modal">&times;</button>
              </div>

              <!-- Modal body -->
              <div class="modal-body">

                <form method="post" action="insert/insertAdmin.php">
                  <!-- Input Text Field-->
                  <div class="input-group mb-2">
                    <div class="input-group-prepend">
                      <span class="input-group-text">Nama Admin</span>
                    </div>
                    <input pattern="[A-Za-z ]+" type="text" class="form-control" required name="nama_admin">
                  </div>
                  <!-- Input Text Field-->
                  <div class="input-group mb-2">
                    <div class="input-group-prepend">
                      <span class="input-group-text">Email</span>
                    </div>
                    <input type="email" class="form-control" required name="emel">
                  </div>
                  <!-- Input Text Field-->
                  <div class="input-group mb-2">
                    <div class="input-group-prepend">
                      <span class="input-group-text">Username</span>
                    </div>
                    <input type="text" class="form-control" required name="username">
                  </div>
                  <!-- Input Text Field-->
                  <div class="input-group mb-2">
                    <div class="input-group-prepend">
                      <span class="input-group-text">Password</span>
                    </div>
                    <input type="password" class="form-control" required name="sandi">
                  </div>
              </div>

              <!-- Modal footer -->
              <div class="modal-footer">
                <!-- Input Button-->
                <input class="btn btn-success" type="submit" value="Simpan"></form>
                <button type="button" class="btn btn-danger" data-dismiss="modal">Tutup</button>
              </div>
            </div>
          </div>
        </div>

        <!-- The Modal Display Lokasi -->
        <div class="modal fade" id="myModalLokasi">
          <div class="modal-dialog modal-xl">
            <div class="modal-content">

              <!-- Modal Header -->
              <div class="modal-header" style="background-color: #47AFAF;">
                <h4 class="modal-title text-light"><i style='font-size:24px' class='fas'>&#xf1de;</i> Daftar Lokasi</h4>
                <button type="button" class="close" data-dismiss="modal">&times;</button>
              </div>

              <!-- Modal body -->
              <div class="modal-body">
                <a href="#" class="btn btn-success" data-toggle="modal" data-target="#myModalTDK"><i style='font-size:20px' class='fas'>&#xf0fe;</i> </a>
                <a href="report/lapKategoriSeluruh.php" target="_blank" class="btn btn-success"><i style='font-size:20px' class='fas'>&#xf1c1;</i> </a>
                <a href="excel/eKategori.php" class="btn btn-success"> <i style='font-size:20px' class='far'>&#xf1c3;</i> </a>
                <br><br>
                <input class="form-control" id="myInputKategori" type="text" placeholder="Cari..">
                <br>
                <div class="table-responsive">
                  <table class="table table-striped table-hover table-sm" id="myTableKategori">
                    <thead>
                      <tr>
                        <th>No</th>
                        <th>Nama Bengkel</th>
                        <th>Nama Lokasi</th>
                        <th> Latitude</th>
                        <th> Longtitude</th>
                        <th>Aksi</th>
                      </tr>
                    </thead>
                    <tbody>
                      <?php
                      $no = 1;
                      $data = mysqli_query($konektor, "SELECT lokasi.id_lokasi,lokasi.id_bengkel,bengkel.nama_bengkel,lokasi.nama_lokasi,lokasi.latitude,lokasi.longtitude FROM lokasi, bengkel WHERE lokasi.id_bengkel = bengkel.id_bengkel");
                      while ($d = mysqli_fetch_array($data)) {
                      ?>
                        <tr>
                          <td><?= $no++; ?></td>
                          <td><?php echo $d['nama_bengkel']; ?></td>
                          <td><?php echo $d['nama_lokasi']; ?></td>
                          <td><?php echo $d['latitude']; ?></td>
                          <td><?php echo $d['longtitude']; ?></td>
                          <td>
                            <a href="#" data-toggle="modal" data-target="#myModalUDK<?php echo $d['id_lokasi']; ?>"><i style='font-size:14px' class='fas'>&#xf044;</i></a>
                            <a onclick="return confirm('Yakin ingin menghapus data sekarang?');" href="delete/deleteLokasi.php?id=<?php echo kunci($d['id_lokasi']); ?>"><i style='font-size:14px' class='fas'>&#xf1f8;</i></a>
                          </td>
                        </tr>

                        <!-- The Modal Ubah Data Lokasi -->
                        <div class="modal fade" id="myModalUDK<?php echo $d['id_lokasi']; ?>">
                          <div class="modal-dialog modal-md">
                            <div class="modal-content">

                              <!-- Modal Header -->
                              <div class="modal-header">
                                <h4 class="modal-title">Ubah Data Lokasi</h4>
                                <button type="button" class="close" data-dismiss="modal">&times;</button>
                              </div>

                              <!-- Modal body -->
                              <div class="modal-body">

                                <!-- Form ubah data menyatu dengan form index-->
                                <form onsubmit="return confirm('Yakin ingin mengubah data sekarang?');" method="post" action="update/updateLokasi.php">
                                  <!--Hidden Field id_lokasi -->
                                  <input type="hidden" name="id_lokasi" value="<?php echo $d['id_lokasi']; ?>">
                                  <!-- Edit List Menu Dinamis-->
                                  <div class="input-group mb-2">
                                    <div class="input-group-prepend">
                                      <span class="input-group-text">Nama Bengkel</span>
                                    </div>
                                    <?php
                                    $data1 = mysqli_query($konektor, "select * from bengkel");
                                    echo "<select class='form-control' required name='id_bengkel'>";
                                    // Mengambil value dari tabel dan disimpan pada variabel $existingid
                                    $existingid = $d['id_bengkel'];
                                    while ($d1 = mysqli_fetch_array($data1)) {
                                      // cek jika $existingid sama dengan yang dipilih untuk ditampilkan
                                      if ($existingid == $d1['id_bengkel'])
                                        echo "<option selected='selected' value='" . $d1['id_bengkel'] . "'>" . $d1['nama_bengkel'] . "</option>";
                                      else
                                        echo "<option value='" . $d1['id_bengkel'] . "'>" . $d1['nama_bengkel'] . "</option>";
                                    }
                                    echo "</select>";
                                    ?>
                                  </div>
                                  <!-- Edit Text Field-->
                                  <div class="input-group mb-2">
                                    <div class="input-group-prepend">
                                      <span class="input-group-text">Nama Lokasi</span>
                                    </div>
                                    <input type="text" class="form-control" required name="nama_lokasi" value="<?php echo $d['nama_lokasi']; ?>">
                                  </div>
                                  <!-- Edit Text Field-->
                                  <div class="input-group mb-2">
                                    <div class="input-group-prepend">
                                      <span class="input-group-text">Latitude</span>
                                    </div>
                                    <input type="text" class="form-control" required name="latitude" value="<?php echo $d['latitude']; ?>">
                                  </div>
                                  <!-- Edit Text Field-->
                                  <div class="input-group mb-2">
                                    <div class="input-group-prepend">
                                      <span class="input-group-text">Longtitude</span>
                                    </div>
                                    <input type="text" class="form-control" required name="longtitude" value="<?php echo $d['longtitude']; ?>">
                                  </div>

                                  <!-- Akhir form ubah data -->

                              </div>

                              <!-- Modal footer -->
                              <div class="modal-footer">
                                <!-- Input Button-->
                                <input class="btn btn-success" type="submit" value="Simpan"></form>

                                <button type="button" class="btn btn-danger" data-dismiss="modal">Tutup</button>
                              </div>
                            </div>
                          </div>
                        </div>

                      <?php } ?>
                    </tbody>
                  </table>
                </div>

                <!-- The Modal Tambah Data Lokasi -->
                <div class="modal fade" id="myModalTDK">
                  <div class="modal-dialog modal-md">
                    <div class="modal-content">

                      <!-- Modal Header -->
                      <div class="modal-header">
                        <h4 class="modal-title"><i style='font-size:20px' class='fas'>&#xf0fe;</i> Tambah Data Lokasi</h4>
                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                      </div>

                      <!-- Modal body -->
                      <div class="modal-body">
                        <form method="post" action="insert/insertLokasi.php">
                          <!-- Edit List Menu Dinamis-->
                          <div class="input-group mb-2">
                            <div class="input-group-prepend">
                              <span class="input-group-text">Nama Bengkel</span>
                            </div>
                            <?php
                            $data1 = mysqli_query($konektor, "select * from bengkel");
                            echo "<select class='form-control' required name='id_bengkel'>";
                            // Mengambil value dari tabel dan disimpan pada variabel $existingid
                            $existingid = $d['id_bengkel'];
                            while ($d1 = mysqli_fetch_array($data1)) {
                              // cek jika $existingid sama dengan yang dipilih untuk ditampilkan
                              if ($existingid == $d1['id_bengkel'])
                                echo "<option selected='selected' value='" . $d1['id_bengkel'] . "'>" . $d1['nama_bengkel'] . "</option>";
                              else
                                echo "<option value='" . $d1['id_bengkel'] . "'>" . $d1['nama_bengkel'] . "</option>";
                            }
                            echo "</select>";
                            ?>
                          </div>
                          <!-- Input Text Field-->
                          <div class="input-group mb-2">
                            <div class="input-group-prepend">
                              <span class="input-group-text">Nama Lokasi</span>
                            </div>
                            <input type="text" class="form-control" required name="nama_lokasi">
                          </div>
                          <!-- Input Text Field-->
                          <div class="input-group mb-2">
                            <div class="input-group-prepend">
                              <span class="input-group-text">Latitude</span>
                            </div>
                            <input type="text" class="form-control" required name="latitude">
                          </div>
                          <!-- Input Text Field-->
                          <div class="input-group mb-2">
                            <div class="input-group-prepend">
                              <span class="input-group-text">Longtitude</span>
                            </div>
                            <input type="text" class="form-control" required name="longtitude">
                          </div>
                      </div>

                      <!-- Modal footer -->
                      <div class="modal-footer">
                        <!-- Input Button-->
                        <input class="btn btn-success" type="submit" value="Simpan"></form>
                        <button type="button" class="btn btn-danger" data-dismiss="modal">Tutup</button>
                      </div>
                    </div>
                  </div>
                </div>



                <script>
                  $(document).ready(function() {
                    $("#myInputKategori").on("keyup", function() {
                      var value = $(this).val().toLowerCase();
                      $("#myTableKategori tr").filter(function() {
                        $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
                      });
                    });
                  });
                </script>
              </div>

              <!-- Modal footer -->
              <div class="modal-footer">
                <button type="button" class="btn btn-danger" data-dismiss="modal">Tutup</button>
              </div>
            </div>
          </div>
        </div>

        <!-- The Modal Display Bengkel -->
        <div class="modal fade" id="myModalBengkel">
          <div class="modal-dialog modal-xl">
            <div class="modal-content">

              <!-- Modal Header -->
              <div class="modal-header" style="background-color: #47AFAF;">
                <h4 class="modal-title text-light">Daftar Bengkel</h4>
                <button type="button" class="close" data-dismiss="modal">&times;</button>
              </div>

              <!-- Modal body -->
              <div class="modal-body">
                <a href="#" class="btn btn-success" data-toggle="modal" data-target="#myModalTDW"><i class="bi bi-plus-lg"></i></a>
                <a href="report/lapWisatawan.php" target="_blank" class="btn btn-success"><i class="bi bi-file-earmark-pdf"></i></a>
                <a href="excel/eWisatawan.php" class="btn btn-success"><i class="bi bi-download"></i></a>
                <br><br>
                <input class="form-control" id="myInputWisatawan" type="text" placeholder="Cari..">
                <br>
                <div class="table-responsive">
                  <table class="table table-striped table-hover table-sm" id="myTableWisatawan">
                    <thead>
                      <tr>
                        <th class="text-center">NO</th>
                        <th class="text-center">Nama Bengkel</th>
                        <th class="text-center">Pemilik</th>
                        <th class="text-center">Telp</th>
                        <th class="text-center">Alamat</th>
                        <th class="text-center">Jam Buka</th>
                        <th class="text-center">Jam Tutup</th>
                        <th class="text-center">Deskripsi</th>
                        <th class="text-center" colspan="2">Aksi</th>
                      </tr>
                    </thead>
                    <tbody>
                      <?php
                      $no = 1;
                      $data = mysqli_query($konektor, "select * from bengkel");
                      while ($d = mysqli_fetch_array($data)) {
                      ?>
                        <tr>
                          <td><?= $no++; ?></td>
                          <td>
                            <a href="berkas/<?= $d['id_bengkel']; ?>.jpg" target="blank"><img class="swing-in-top-fwd" src="berkas/<?= $d['id_bengkel']; ?>.jpg" width="70" height="70" /></a>
                            <?= $d['nama_bengkel']; ?>
                          </td>
                          <td><?= $d['nama_pemilik']; ?></td>
                          <td><?= $d['no_hp']; ?></td>
                          <td><?= $d['alamat']; ?></td>
                          <td><?= $d['jam_buka']; ?></td>
                          <td><?= $d['jam_tutup']; ?></td>
                          <td><?= $d['deskripsi']; ?></td>
                          <td>
                            <a href="#" class="btn btn-warning" data-toggle="modal" data-target="#myModalUDW<?= $d['id_bengkel']; ?>"><i class="bi bi-pencil-square"></i></a>
                          </td>
                          <td>
                            <a class="btn btn-danger" onclick="return confirm('Yakin ingin menghapus data sekarang?');" href="delete/deleteBengkel.php?id=<?= kunci($d['id_bengkel']); ?>"><i class="bi bi-trash3"></i></a>
                          </td>
                        </tr>

                        <!-- The Modal Ubah Data Bengkel -->
                        <div class="modal fade" id="myModalUDW<?= $d['id_bengkel']; ?>">
                          <div class="modal-dialog modal-lg">
                            <div class="modal-content">

                              <!-- Modal Header -->
                              <div class="modal-header">
                                <h4 class="modal-title">Ubah Data Bengkel</h4>
                                <button type="button" class="close" data-dismiss="modal">&times;</button>
                              </div>

                              <!-- Modal body -->
                              <div class="modal-body">

                                <!-- Form ubah data menyatu dengan form index-->
                                <form onsubmit="return confirm('Yakin ingin mengubah data sekarang?');" method="post" enctype="multipart/form-data" action="update/updateBengkel.php">
                                  <!--Hidden Field id_bengkel -->
                                  <input type="hidden" name="id_bengkel" value="<?= $d['id_bengkel']; ?>">

                                  <!-- Edit File Field-->
                                  <div class="input-group mb-2">
                                    <div class="input-group-prepend">
                                      <span class="input-group-text">Upload Gambar</span>
                                    </div>
                                    <input type="file" class="form-control" required name="file_bengkel">
                                  </div>
                                  <!-- Edit Text Field-->
                                  <div class="input-group mb-2">
                                    <div class="input-group-prepend">
                                      <span class="input-group-text">Nama Bengkel</span>
                                    </div>
                                    <input pattern="[A-Za-z ]+" type="text" class="form-control" required name="nama_bengkel" value="<?= $d['nama_bengkel']; ?>">
                                  </div>
                                  <!-- Edit Text Field-->
                                  <div class="input-group mb-2">
                                    <div class="input-group-prepend">
                                      <span class="input-group-text">Nama Pemilik</span>
                                    </div>
                                    <input pattern="[A-Za-z ]+" type="text" class="form-control" required name="nama_pemilik" value="<?= $d['nama_pemilik']; ?>">
                                  </div>

                                  <!-- Edit Text Field-->
                                  <div class="input-group mb-2">
                                    <div class="input-group-prepend">
                                      <span class="input-group-text">Telepon</span>
                                    </div>
                                    <input class="form-control" required type="number" name="no_hp" value="<?= $d['no_hp']; ?>">
                                  </div>

                                  <!-- Edit Text Field-->
                                  <div class="input-group mb-2">
                                    <div class="input-group-prepend">
                                      <span class="input-group-text">Alamat</span>
                                    </div>
                                    <input class="form-control" required type="text" name="alamat" value="<?= $d['alamat']; ?>">
                                  </div>
                                  <!-- Edit Text Field-->
                                  <div class="input-group mb-2">
                                    <div class="input-group-prepend">
                                      <span class="input-group-text">Jam Buka</span>
                                    </div>
                                    <input class="form-control" required type="time" name="jam_buka" value="<?= $d['jam_buka']; ?>">
                                  </div>
                                  <!-- Edit Text Field-->
                                  <div class="input-group mb-2">
                                    <div class="input-group-prepend">
                                      <span class="input-group-text">Jam Tutup</span>
                                    </div>
                                    <input class="form-control" required type="time" name="jam_tutup" value="<?= $d['jam_tutup']; ?>">
                                  </div>
                                  <!-- Edit Text Field-->
                                  <div class="input-group mb-2">
                                    <div class="input-group-prepend">
                                      <span class="input-group-text">Deskripsi</span>
                                    </div>
                                    <input class="form-control" required type="text" name="deskripsi" value="<?= $d['deskripsi']; ?>">
                                  </div>
                                  <!-- Akhir form ubah data -->

                              </div>

                              <!-- Modal footer -->
                              <div class="modal-footer">
                                <!-- Input Button-->
                                <input class="btn btn-success" type="submit" value="Simpan"></form>
                                <button type="button" class="btn btn-danger" data-dismiss="modal">Tutup</button>
                              </div>
                            </div>
                          </div>
                        </div>

                      <?php } ?>
                    </tbody>
                  </table>
                </div>

                <!-- The Modal Tambah Data Bengkel-->
                <div class="modal fade" id="myModalTDW">
                  <div class="modal-dialog modal-md">
                    <div class="modal-content">

                      <!-- Modal Header -->
                      <div class="modal-header">
                        <h4 class="modal-title"><i style='font-size:20px' class='fas'>&#xf0fe;</i> Tambah Data Bengkel </h4>
                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                      </div>

                      <!-- Modal body -->
                      <div class="modal-body">

                        <form method="post" action="insert/insertBengkel.php" enctype="multipart/form-data">
                          <!-- Input File Field-->
                          <div class="input-group mb-2">
                            <div class="input-group-prepend">
                              <span class="input-group-text">Upload Gambar</span>
                            </div>
                            <input type="file" class="form-control" required name="file_bengkel">
                          </div>
                          <!-- Input Text Field-->
                          <div class="input-group mb-2">
                            <div class="input-group-prepend">
                              <span class="input-group-text">Nama Bengkel</span>
                            </div>
                            <input pattern="[A-Za-z ]+" type="text" class="form-control" required name="nama_bengkel">
                          </div>
                          <!-- Input Text Field-->
                          <div class="input-group mb-2">
                            <div class="input-group-prepend">
                              <span class="input-group-text">Nama Pemilik</span>
                            </div>
                            <input type="text" class="form-control" required onkeypress="return event.charCode <=47 || event.charCode >=58" name="nama_pemilik">
                          </div>

                          <!-- Input Text Field-->
                          <div class="input-group mb-2">
                            <div class="input-group-prepend">
                              <span class="input-group-text">Telepon</span>
                            </div>
                            <input maxlength="12" length="12" type="text" onkeypress="return event.charCode >=48 &&  event.charCode <=57" class="form-control" required name="no_hp">
                          </div>

                          <!-- Input Text Field-->
                          <div class="input-group mb-2">
                            <div class="input-group-prepend">
                              <span class="input-group-text">Alamat</span>
                            </div>
                            <input type="text" class="form-control" required name="alamat">
                          </div>
                          <!-- Input Text Field-->
                          <div class="input-group mb-2">
                            <div class="input-group-prepend">
                              <span class="input-group-text">Jam Buka</span>
                            </div>
                            <input type="time" class="form-control" required name="jam_buka">
                          </div>
                          <!-- Input Text Field-->
                          <div class="input-group mb-2">
                            <div class="input-group-prepend">
                              <span class="input-group-text">Jam Tutup</span>
                            </div>
                            <input type="time" class="form-control" required name="jam_tutup">
                          </div>

                          <!-- Input Text Field-->
                          <div class="input-group mb-2">
                            <div class="input-group-prepend">
                              <span class="input-group-text">Deskripsi</span>
                            </div>
                            <input type="text" class="form-control" required name="deskripsi">
                          </div>
                      </div>

                      <!-- Modal footer -->
                      <div class="modal-footer">
                        <!-- Input Button-->
                        <input class="btn btn-success" type="submit" value="Simpan"></form>
                        <button type="button" class="btn btn-danger" data-dismiss="modal">Tutup</button>
                      </div>
                    </div>
                  </div>
                </div>

                <script>
                  $(document).ready(function() {
                    $("#myInputWisatawan").on("keyup", function() {
                      var value = $(this).val().toLowerCase();
                      $("#myTableWisatawan tr").filter(function() {
                        $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
                      });
                    });
                  });
                </script>
              </div>

              <!-- Modal footer -->
              <div class="modal-footer">
                <button type="button" class="btn btn-danger" data-dismiss="modal">Tutup</button>
              </div>
            </div>
          </div>
        </div>

      </div>
      <div class="col-sm-6">
        <!--konten kolom 2 -->

        <!--Mulai grafik-->
        <center class="text-light font-weight-bold">GRAFIK STATUS Bengkel</center>
        <div style="width: 100%;margin: 0px auto;">
          <canvas id="myChart"></canvas>
        </div>
        <script>
          var ctx = document.getElementById("myChart").getContext('2d');
          var myChart = new Chart(ctx, {
            type: 'pie', //bar: batang, pie: lingkaran, line: garis, 
            data: {
              labels: ["Punlikasi", "Tunda"],
              datasets: [{
                label: '',
                data: [
                  <?php
                  $jumlah_data_1 = mysqli_query($konektor, "SELECT * from tbl_objekwisata where status='1'");
                  echo mysqli_num_rows($jumlah_data_1); //Menghitung jumlah record kolom 1
                  ?>,
                  <?php
                  $jumlah_data_2 = mysqli_query($konektor, "SELECT * from tbl_objekwisata where status='0'");
                  echo mysqli_num_rows($jumlah_data_2); //Menghitung jumlah record kolom 2
                  ?>
                ],
                //R: red, G: Green, B: Blue, A: Alpha (Mengatur transparansi warna)
                backgroundColor: [
                  'rgba(219, 162, 4, 0.2)', //Warna isi grafik kolom 1
                  'rgba(31, 204, 8, 0.2)' //Warna isi grafik kolom 2
                ],
                borderColor: [
                  //R: red, G: Green, B: Blue, A: Alpha (Mengatur transparansi warna)
                  'rgba(219, 162, 4, 1)', //Warna border grafik kolom 1
                  'rgba(31, 204, 8, 1)' //Warna border grafik kolom 2
                ],
                borderWidth: 1
              }]
            },
            options: {
              scales: {
                yAxes: [{
                  ticks: {
                    beginAtZero: true
                  }
                }]
              }
            }
          });
        </script>
        <!--Selesai grafik-->



      </div>
    </div>
  </div>

  <script>
    const messageSuccess = $('.message-success').data('message-success');
    const messageInfo = $('.message-info').data('message-info');
    const messageWarning = $('.message-warning').data('message-warning');
    const messageDanger = $('.message-danger').data('message-danger');

    if (messageSuccess) {
      Swal.fire({
        icon: 'success',
        title: 'Berhasil Terkirim',
        text: messageSuccess,
      })
    }

    if (messageInfo) {
      Swal.fire({
        icon: 'info',
        title: 'For your information',
        text: messageInfo,
      })
    }
    if (messageWarning) {
      Swal.fire({
        icon: 'warning',
        title: 'Peringatan!!',
        text: messageWarning,
      })
    }
    if (messageDanger) {
      Swal.fire({
        icon: 'error',
        title: 'Kesalahan',
        text: messageDanger,
      })
    }
  </script>
</body>

</html>